name:  CI

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:

  test-ubuntu:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-24.04]

    name: test-${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies (apt)
        run: |
          sudo apt-get update -y -qq
          sudo apt -y install mono-mcs wget

      - name: Build Debug
        run: |
          ./build.sh debug
          ./build-test.sh

      - name: Run Test
        run: |
          cd build/test/net20
          mono ./wstest.exe
          mkdir lib
          mv c-wspp* lib/
          mono ./wstest.exe ./lib


  test-windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: msys2/setup-msys2@v2
        with:
          update: true
          pacboy: mono:p wget:p

      - name: Install dependencies
        run: |
          pacman --noconfirm -S unzip

      - name: Build Debug
        run: |
          ./build.sh debug
          ./build-test.sh

      - name: Run Test
        run: |
          cd build/test/net20
          ./wstest.exe
          mkdir lib
          mv c-wspp* lib/
          ./wstest.exe lib

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Run Test (32bit)
        shell: pwsh
        run: |
          cd build/test/net20
          CorFlags.exe wstest.exe /32BIT+
          ./wstest.exe lib
